/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	metricsrouteriov1alpha1 "github.com/arjunrn/custom-metrics-router/pkg/apis/metricsrouter.io/v1alpha1"
	versioned "github.com/arjunrn/custom-metrics-router/pkg/client/clientset/versioned"
	internalinterfaces "github.com/arjunrn/custom-metrics-router/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/arjunrn/custom-metrics-router/pkg/client/listers/metricsrouter.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomMetricsSourceInformer provides access to a shared informer and lister for
// CustomMetricsSources.
type CustomMetricsSourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CustomMetricsSourceLister
}

type customMetricsSourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCustomMetricsSourceInformer constructs a new informer for CustomMetricsSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomMetricsSourceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomMetricsSourceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCustomMetricsSourceInformer constructs a new informer for CustomMetricsSource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomMetricsSourceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsrouterV1alpha1().CustomMetricsSources().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MetricsrouterV1alpha1().CustomMetricsSources().Watch(context.TODO(), options)
			},
		},
		&metricsrouteriov1alpha1.CustomMetricsSource{},
		resyncPeriod,
		indexers,
	)
}

func (f *customMetricsSourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomMetricsSourceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customMetricsSourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metricsrouteriov1alpha1.CustomMetricsSource{}, f.defaultInformer)
}

func (f *customMetricsSourceInformer) Lister() v1alpha1.CustomMetricsSourceLister {
	return v1alpha1.NewCustomMetricsSourceLister(f.Informer().GetIndexer())
}
