apiVersion: v1
kind: Service
metadata:
  labels:
    app: custom-metrics-router
  name: custom-metrics
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    app: custom-metrics-router
  type: ClusterIP
